# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84672fac23ec9d1c9ddad2ff3b134253eb7c1324ae5e408b12c52919627e95eb5cdfa0d294bf1f65e1e14bd9c950a3d0746c5c6da2c195caebe9b72682249c57

test:
  secret_key_base: 68090559fdc8124ff326e2fbbd7451b8732ed0de78c3c2afc52e86a9e37d58cce2449097995e5b41006fd5535598a8c9b040f218ce9f8d059c3d3a2100bb61ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
